### ISSUE TITLE
Auto-save progress after each kanji instead of at the end

### ISSUE THREAD

**Issue by Ericchi** [SYtor/Kanji-Dojo#106]
It happened a couple of times already that I had to do stuff with my phone while I was drawing kanji and the app closed itself in the background. When I returned to the app, my progress was reset because I didn't complete the session. Is it possible to have it save after each kanji instead of at the end of the session?

**Comment by syt0r** [comment]
I see, the system probably killed Kanji Dojo's process after some time while idling. There is a way to save and restore state, restoration will work if you don't manually close the app, but it might be complicated to implement. For now try doing smaller number of reviews

**Comment by martinetd** [comment]
Maybe as a compromise (since state restoration is more difficult) we could make exiting the current session save progress up till the last kanji reviewed?
Given one sometimes/usually wants to adjust some kanjis scheduled as "bad" at the end of a session I don't think automatically committing something would be appropriate, but removing all kanjis not seen yet and going to the standard end of session screen is probably doable.

(I haven't had this bite me yet, but when reviewing during commute I usually make sets smaller than I have to and create a new set again a few times -- it'd be more efficient to schedule as much as is available and just let me stop when reaching the last stop)

**Comment by syt0r** [comment]
Now progress is saved immediately in version 2.1.0
