### ISSUE TITLE
Kanji Dojo 1.9 - slight delay in loading the main screen.

### ISSUE THREAD

**Issue by ThomasLeigh** [SYtor/Kanji-Dojo#109]
I have a few character sets on the main screen. Before I've upgraded to 1.9 this screen showed up instantaneously after I've launched the app. After upgrading to 1.9 ver. there is a slight delay before the main screen is showed, I see a progress bar.

I don't expect the app to work immediately, lightning fast all the time, especially given aging devices. The reason I'm pointing this out is that some time ago You have fixed another delay (the one which had been distinctively visible) - which was a great surprise and relief. So maybe my post would be of value for you and maybe this time also the elimination of the delay is possible.

![Screenshot_2024-02-20-19-12-38-311_ua syt0r kanji fdroid](https://github.com/syt0r/Kanji-Dojo/assets/26142231/325463f1-f9f8-4726-9f72-8ef90fbb6221)

**Comment by syt0r** [comment]
Not much was changed on this screen in 1.9 version update except for loading state UI, maybe it just made loading more noticeable. The delay you mentioned was happening because I forgot to add initial prefetch of the data for the second item in review queue, but there's nothing to speed up here because this screen loads data immediately
