### ISSUE TITLE
Add sound

### ISSUE THREAD

**Issue by Pantyhose-X** [SYtor/Kanji-Dojo#11]
The voice reads automatically, so I can learn to pronounce it while writing by hand.

## off-topic
I really hate kanji. Japanese Hiragana Katakana, it's cool and easy to learn.

The Japanese government doesn't do anything useful, and never abolished kanji.
Korean abolished kanji a long time ago

**Comment by syt0r** [comment]
Hey. It can definitely be done for kana, but since there are multiple kanji readings it's not clear which pronunciation to play.

By the way I already tried to use android's system text-to-speach to voice kana's romaji but unfortunately quality is not very good, so I guess it will be necessary to ship dedicated sound files

I think kana voicing can be implemented, but I don't feel that it's would be very useful feature, so this task is low priority

**Comment by Fortfite** [comment]
> Hey. It can definitely be done for kana, but since there are multiple kanji readings it's not clear which pronunciation to play.
> 
> By the way I already tried to use android's system text-to-speach to voice kana's romaji but unfortunately quality is not very good, so I guess it will be necessary to ship dedicated sound files
> 
> I think kana voicing can be implemented, but I don't feel that it's would be very useful feature, so this task is low priority

I know this is a year late but you can get massively improved pronunciation by setting the Android TTS language to Japanese rather than English/system default. 

![Screenshot_20240210-105708](https://github.com/syt0r/Kanji-Dojo/assets/58756672/46b41a7d-0bda-488f-aca5-e10b21377e47)
