### ISSUE TITLE
Fuzzy/pixelated lines in writing practice area

### ISSUE THREAD

**Issue by MailYouLater** [SYtor/Kanji-Dojo#12]
I recently discovered this app, and I like it, but there's one thing that I find really annoying.  Both the demonstration and user input lines in the writing practice area are quite pixelated and fuzzy, like they are being rendered at a lower resolution and scaled up.  The screenshots in the readme and on both the F-Droid and Google Play listings seem to show lines with sharper, crisper edges, so I'm guessing the issue either got introduced in an update, or doesn't affect all devices.

I've included a screenshot of the issue as seen in version 1.1 on a Samsung Galaxy S7 Edge (Model SM-G935V) running Android 8.
Notes:
- My phone has options to render the display at 1280x720, 1920x1080, and 2560x1440.  This issue is present at all of these resolutions.
- This screenshot is from the F-Droid release, but I also tested with the Google Play version, and the APK downloaded from this GitHub project's releases page.  They all behaved the same.
- The colored demo graphic above looks like it might be a little pixelated too, but it's not as obvious because it's smaller.

![Screenshot](https://user-images.githubusercontent.com/1279475/222028808-ecf0e360-5e4a-47d6-9d66-6e361c2ac56d.jpg)

**Comment by syt0r** [comment]
Thank you for report, this is definitelly a critical bug, will try to fix it asap

**Comment by syt0r** [comment]
Looks like these issues are related to hardware acceleration on older android OS so the behaviour is different, here are some details:
- Path effect for `drawLine` is not supported so it draws straight line instead of dashed line, I replaced straight line with rectangles, issue details [here](https://issuetracker.google.com/issues/236553602)
- Canvas scale is scaling bitmap made from unscaled path instead of generating bitmap after scale, fixed by replacing canvas scale with path transformation matrix, details [here](https://issuetracker.google.com/issues/36956831) 

@MailYouLater I would appreciate if you could verify fixes on this debug version of the app, note - some features are broken right now: https://drive.google.com/file/d/10x7hsC-ji3Us99o5nkY5O5aKVkMRqH2d/view?usp=sharing

**Comment by MailYouLater** [comment]
Confirmed.  The lines in the writing practice area are nice and sharp in the provided development test build.

Also, thank you for including your analysis, as well as the quick turnaround time on this fix.  Very impressed.

![Screenshot](https://user-images.githubusercontent.com/1279475/222206690-9158a7a2-670e-461f-a840-73d6396fb015.jpg)

**Comment by syt0r** [comment]
Great, thanks for the help. I'm going to release new version with this fix in about 1-2 weeks

**Comment by syt0r** [comment]
Done, available in version 1.2
