### ISSUE TITLE
Calligraphic drawing style.

### ISSUE THREAD

**Issue by ThomasLeigh** [SYtor/Kanji-Dojo#126]
I'm very happy to know such a well-done, aesthetic and elegant app for drawing Kana and Kanji. In my native language I've already recorded and [published](https://www.youtube.com/playlist?list=PL8yelphAn7syIYcbBx9fNtccmt7_O6khl) a few podcast episodes on learning Japanese, in which I describe and preach about Kanji Dojo :) (new episodes are in store) . 

Learning Japanese is relatively new for me (almost a year now). Given that now this learning provides me with a refreshed perspective on everything Japanese, I've decided to re-watch an anime called "Barakamon". Its protagonist is a calligrapher drawing with love and passion, and this is why I am especially interested in watching this anime again: after learning and drawing over a thousand characters, and all the pleasure I gain out of it, watching this particular anime is much more interesting than ever.

Note that drawing characters within Kanji Dojo may often resemble calligraphy, at least to some degree - mostly because strokes in this app look aesthetically, i.a., thanks to their thickness. I wonder would it be possible to apply an additional stroke style which could definitely look like calligraphy drawing, like a drawing brush? It could add an additional, tangible taste to the everyday experience with Kanji Dojo, making the drawing practice heavenly pleasant for each drawing passionate student :) .

**Comment by syt0r** [comment]
I know this one, I've read the manga 😅 . It would be a cool feature, but I don't think it's possible, at least without too much efforts. Generally when drawing on canvas it's possible to only use either round or rectangular strokes cap. Strokes from KanjiVG are also prepared in a specific way, they are simpler than strokes from default fonts because they only represent direction, like a one way line, on the other hand normal vector fonts consist of an inner and outer closed contours filled with color allowing more details, so it would require to come up with some algorithm to generate this complicated shape when drawing, interpolate it for the stroke detection algorithm, animate it, and somehow access and handle vector data from fonts, I don't even know if there's an API for this so I don't think I can handle this on my own
