### ISSUE TITLE
Words writing mode for vocab practice 

### ISSUE THREAD

**Issue by syt0r** [SYtor/Kanji-Dojo#143]

**Comment by ThomasLeigh** [comment]
**Fantastic thing**, thank You very much for introducing that! Could You please allow live correction by each stroke, like in the case of single character practice? I think it is one of the most valuable characteristics of the app to allow a student to be **constantly** exposed to the perfect character's look / appearance.

**Comment by ThomasLeigh** [comment]
Btw. I've dreamed of such a feature (writing words character by character). Thank Yooouuuu so so much! Now the only things remained in this case are SRS or SuperMemo alongside mark system and custom decks (custom decks seem to be already implemented, I need to take a closer look).

Do you consider implementing SRS for vocabulary writing practice?

**Comment by syt0r** [comment]
I plan to add srs but only for flashcards mode. Oh, right, forgot to close this issue

**Comment by ThomasLeigh** [comment]
I apologize to keep posting while You've closed this issue, I'm not sure should I start new threads to discuss remaining points which I find worth attention... Should I?


> I plan to add srs but only for flashcards mode

SRS is fantastic in learning, thanks to this I have no problem with maintaining over a thousand characters optimally within my mind / memory. I find fantastic the ability to automatically schedule right characters to review for today, tomorrow, etc. It's crucial. Let alone SuperMemo openly available algorithm, if You would like to implement it.

If you would be able to implement SRS also into words writing mode, it could spread the same crucial learning strength over perfecting ability of literally writing in Japanese, which imho would elevate the app's value even higher, significantly higher - because still there are many people who learn in order to be able to actually write. At least I strongly believe that.

**Please consider to implement SRS also into words writing mode**.


**Another important question**: could you allow users to use live correction per stroke (like in case of single character practice) within words writing mode?
