### ISSUE TITLE
Vocabulary decks contain some unusual words

### ISSUE THREAD

**Issue by ramonls8** [SYtor/Kanji-Dojo#193]
The 日本語能力試験 vocabulary decks contain more terms and words than usual, many of which are not commonly used.

Some of these words do not even appear on the Japanese keyboard when entering hiragana, and some of them do not even appear in the dictionary.

Some examples for the N2 vocabulary deck are:
爻辞、書笈、爻、鸛、国府、亢、篠、出納、辶、大簇、斉、暹、軫。

This deck (N2) has 2924 words, which is more than other N2 vocabulary lists I have found on the Internet, which have about 1500 words.

Here are some lists you can use as reference:

* [Anki N1 to N5 decks](https://ankiweb.net/shared/info/1550984460)
* [jlptmatome N2 vocabulary list](https://www.jlptmatome.com/jlpt-n2-vocabulary-list/)

**Comment by syt0r** [comment]
This is a known issue, I've added a note that lists are experimental because of it. Currently app needs an association for each word with word id from jmdict dictionary and my lookup method returns some extra words with the same readings. Here's the data, it has to be manually reviewed to reduce entries that have more than one id:  https://github.com/syt0r/Kanji-Dojo-Data/blob/master/data/vocab_decks/n5.json

There's actually a project with mapping, but due to missing licensing info I'm not sure whether I can use it 
https://github.com/stephenmk/yomichan-jlpt-vocab

**Comment by syt0r** [comment]
Updated in 2.1.3, should be better now
