### ISSUE TITLE
Improve app usage retention

### ISSUE THREAD

**Issue by syt0r** [SYtor/Kanji-Dojo#24]
According to analytics user retention is not very good, people are either don't want to use the app but keep it installed or just slacking off

![image](https://user-images.githubusercontent.com/7478653/226167936-640bec87-e8a7-408a-ad73-90dfdd865693.png)

I'd like to give users a little push to keep them study. I think following features would help:
1. Practice daily strike calendar, or something similar. Can put it either on top of practice dashboard screen or make a new screen for it
2. Reminder notification. It might contain not only action button to enter application but also a useful information, like info about character that is pending for review, etc

**Comment by sercero** [comment]
Hello @syt0r,

First of all congratulations on the great app and thanks for making it open source, very cool.

I'm replying to this issue because I really like this app, but I think that it can improve greatly for new users with some changes.
In my opinion it would be best if the app was more opinionated and guided the user more in the WaniKani style.
That is, present three paths: Hiragana, Katakana and Kanji
The user is taken through the levels learning 5 characters at a time.
Then after some time and due to the SRS algorithm evaluating the user according to the caracters where they made mistakes.

So, what should change:
 - Suppose you are in the Hiragana page and you press "play" then the program should evaluate the user on the failed characters and not some random selection
   The play button should give no options and just take the user through the caracters that are orange or red.
 - The next and retry button are confusing, if the user made a mistake then the character should be evaluated again (the retry button could be activated in settings)
 - Use one of the known SRS algorithms, in my experience the app has a very long time to ask for evaluation of a character something is wrong there.
 - I also think that the feature to give the user the ability to mix and match characters is also confusing for new people, there should be more handholding.

I understand that perhaps these changes will upset the people that have been using the app for a long time so the current behaviour could be configured through settings.

Just my 2 cents as a new user.

**Comment by syt0r** [comment]
@sercero  Thank you for the suggestions. I agree, button labels might sound confusing, I will probably rename them to "Good" and "Bad", similar to Anki. 

The next version will include automated options to start practice without going inside and seeing an overwhelming list of characters with statuses. I've also already remade my srs algorithm and database structure for it so hopefully it will be better, maybe later on I'll add an option to manually set srs interval multiplier as well.

I don't want to be too pushy with "Repeat" button since the stroke detection algorithm is far from perfect and users can evaluate their recall ability by themselves anyway

**Comment by nab4444** [comment]
Something similar to github green squares showing the amount of reps each day would be a great motivation booster imo

**Comment by syt0r** [comment]
Closing this for now, need to think of more improvements to stats later
