### ISSUE TITLE
Adjust Review Frequency 

### ISSUE THREAD

**Issue by themangosteen** [SYtor/Kanji-Dojo#29]
It would be great to be able to adjust the time after which the color indicator for a group changes from "Recently reviewed" to "Review recommended".

Ideally there could be different intervals depending on how often it has been reviewed so far, as well the option to no longer recommend review after a certain number of completions or by manual setting it to done don't remind me anymore for a group.

This has psychological effects on motivation and satisfaction, the indicator going back to review recommended each day may create an invalidating feeling. By allowing the user to have their learning reflected in the review indicator it can create a feeling of satisfaction and success.

Thank you for the wonderful app! It has become my favorite learning app for kanji together with a book.

**Comment by syt0r** [comment]
Glad you like the application. I agree that giving control over review intervals would be helpful and make algorithm clearer from user perspective. Overall I tried to imitate Anki's review mechanism although I did not invest a lot of efforts to understand how it actually works. 

By the way, right now there is following behaviour:
- you have to write character with not more than 2 mistakes a day, otherwise it resets review period
- character is considered as reviewed if you reviewed it more days than square root of count of days since first correct review day
- and it's considered reviewed as well if you reviewed it successfully more than 5 days ago and reviewed it successfully again, it will be considered as reviewed twice this interval

**Comment by themangosteen** [comment]
Thanks for writing the current mechanism, that sounds really reasonable! :) I guess I just made too many mistakes then haha :)

**Comment by syt0r** [comment]
Maybe, or perhaps there is a bug :sweat_smile:. I actually had to delete app from my phone to test update and lost all my progress, so it would be worth to verify it with next update as well as fix corresponding unit test I recently broke with refactor))

**Comment by syt0r** [comment]
I don't think it's relevant anymore, new version is more clear regarding next review interval and have more options
