### ISSUE TITLE
Be more strict

### ISSUE THREAD

**Issue by kanji-deshi** [SYtor/Kanji-Dojo#38]
Currently, the kanji writing practice tolerates up to 2 mistakes. This leads to some kanji not being properly learned, like always guessing the order of the first two strokes of 左 and 右.
While I understand why you wouldn't want the review period to be reset from just a few mistakes, I'd prefer something like kanjis being kept in the queue until they are drawn without mistakes and whether to reset the review period being decided based on the total count of mistakes since the last time the kanji was drawn without mistakes.

**Comment by syt0r** [comment]
I understand your concern, I myself sometimes intentionally make additional mistakes if I was able to guess character with few mistakes which is weird UX to trigger mistake. Unfortunatelly my stroke detection algorithm is not perfect and I often notice that there are false positive errors when writing small or complicated strokes, this is why I allowed to make up to 2 mistakes for writing practice, but 0 for reading. I'm thinking about how to make it more customizable alongside with #29 feature. My current idea is to add option to settings screen like SRS (Spaced repetition system) configuration that opens new screen where you can adjust:
1. review intervals (now it's square root of days count with reviews without mistakes, I want to add a more options with example chart)
2. separate toleranted mistakes count for writing and reading
3. and maybe an option to make repeat button automatically be considered as mistake

On a second thought points 2 and 3 are not very flexible because configuration would be applied to all repeats automatically and can be replaced with additional button on practice screen but idk how to fit it into layout

The other idea would be not to save practice results automatically on summary screen, but to allow user to toggle characters that have mistakes and should be repeated next day

Quite a lot of options so I'm still thinking which is the best one 😅

**Comment by kanji-deshi** [comment]
Thanks for your detailed answer.

I'm still unsure how the current algorithm works. Let's say I draw a kanji with 2 mistakes and hit the red button. Then I draw it again with 1 mistake and hit the green button. Will the review period reset (because the total count of mistakes is higher than 2)? If so, I think all I need is a way to lower the limit for the green button to appear.

I think of this app as a(n actually pretty fun) game. However that also means that I never hit a red button unless I have to. I don't even keep track of how many mistakes I made so just having the count displayed somewhere while drawing would already help.

**Comment by syt0r** [comment]
Sorry for late reply. Application counts total mistakes for a character, as shown in summary, more than 2 and red highlight means interval reset.

I think there is no need to lower limit for green button because you can always pick retry option yourself, right?

I'm thinking to stick to the option with manual selection of characters for which interval should be reseted on the summary screen, there it would be possibly to make adjustable mistakes count threshold for automatic preselection and further adjust selection manually. With this solution 2 buttons(repeat and next) can be shown all the time and it would be up to the user to decide whether to practice more or less, pretty flexible imho

**Comment by kanji-deshi** [comment]
Thanks for the clarification. Theoretically, I could always pick retry myself, I just don't want to make that decision every time. It's OK though, I managed to build my own version. (I changed CharacterMistakesToRepeat from WritingPracticeInputSection.kt)
