### ISSUE TITLE
Enhancement Request: Set all the configurations and preferences in the main settings, not the Practice Settings

### ISSUE THREAD

**Issue by polandreh** [SYtor/Kanji-Dojo#51]
The Practice Configuration is not practical. 
These options don't need to be reminded every time we start a new practice: 
- users won't suddenly turn right-handed depending on the characters they're reviewing; 
- the "Study new characters" option becomes obsolete once we've 100% the set; 
- and, at least me, will prefer to have all my practices randomized, and the hints (translation layout) hidden by default.

These configurations would be better placed in the main page's settings.

Starting a practice already takes too many steps: 

- Select the Practice.
- Select the group you want to practice, or the option to select multiple groups. Then, select the groups.
- Press Play.
- Select how many characters you want in the Review options.
- Confirm Practice Configuration settings.
and then you can finally start.

If we can cut the number of steps by at least one, it's already a win.

**Comment by syt0r** [comment]
I introduced this practice configuration step mainly because of "shuffle" and "learn new" configurations, previously they could be  toggled inside of the optional dialog on practice details screen in a bottom sheet, but since now practice can be started from dashboard screen as well I decided to move all configurations to a single place
I think it's fairly easy to ignore configurations once you configured them initially and just click on start button. I'm also planning to add there an option to download and manage kana voices. From my understanding it's also more clear from user perspective to see all available options in one place

**Comment by polandreh** [comment]
Then, maybe could you merge the Review Options with the Practice Configuration? Along with the Shuffle and Hide Translation options, you could include the sliding bar of the number of kanjis to be reviewed at the bottom (there should be enough space). It would reduce the number of buttons needed to start a practice.

I still think the Left-Handed option should go into the global settings, as people won't change dexterity just because it's a different practice.
