### ISSUE TITLE
Add information to distinguish kanji variants

### ISSUE THREAD

**Issue by ghost** [SYtor/Kanji-Dojo#94]
As I explained in the recent issue (#90), there's currently no way to distinguish between variant forms.

I suggest adding an option that shows the number of strokes so that in most cases I can know what form the answer is.

I think this is a good idea because things about itaiji are complicated and sometimes controversial.

**Comment by AttractLight** [comment]
I've organized my thoughts on this issue. I leave cons of each ideas.

Always show stroke count
* Stroke count might be a hint for **all kanji** (in a positive way, stroke count could be additional knowledge?)
* Unable to judge variants with the same stroke count (e.g. 収 & 收, 劒 & 劔)
* Users need to remember stroke count of each kanji

Show stroke count if kanji has variants
* Whether or not showing the existence of variants might be a hint
* Unable to judge variants with the same stroke count
* Users need to remember stroke count of each kanji

Show variants
* Variants themselves might be a hint of composition (i.e. it's easy to guess 儉 from 倹, 檢 from 検 etc. while they have similar readings)

Show a hint of the first stroke if kanji has variants
* Not so helpful

### When to show if not always?
* If kanji has variants (shows on 剣, 劍, 劒, 劔)
* If the kanji is not Joyo and has variants (shows on 劍, 劒, 劔)

### What variants?
* available on Kanji Dojo - most practical
* available on JIS and/or relatively tiny databases - may be helpful for new users
* exists on Earth - would be too annoying

**Comment by syt0r** [comment]
I see, so info regarding stroke count is not a guarantee that variants can be distinguished. I think it's important to allow users distinguish characters by default. If it's not possible to do with stroke count, how about adding a label with character's code?

I just found one of the characters you mentioned in kanjidic2 file and seems it provides some info about variants
![image](https://github.com/syt0r/Kanji-Dojo/assets/7478653/8c664306-673f-4ab6-bf3b-3b141d391a74)

I could write a script to filter characters that have variants and get their jis208 codes, if it won't be a huge list I could hardcode those values in the app. These codes will be shown only for characters that have variants. Maybe it;s possible to get jis208 codes programmatically as well, so it would be required to only find characters with variants

Is there any other way natives use to distinguish kanji variants? Because it's quite a technical info :sweat_smile:

**Comment by AttractLight** [comment]
Yes, JIS codepoints are too technical and also not useful these days... (Unicode codepoints should be better in this case).

I'm not a CJKV expert at all, but I believe there's no other way to distinguish variants since their differences are only in form.

After all, showing characters of those variants recorded in kanjidic2 should be most helpful and simple.

This is not necessary at all but I found a database which records shinjitai and kyujitai in a troublesome way (using Variation Selectors): https://github.com/cjkvi/cjkvi-variants/blob/master/jp-old-style.txt

btw I'm a little surprised JIS X 0208 had more variants of 剣 than I knew.

**Comment by syt0r** [comment]
Then how about we add a unicode code and right next to it a hidden text with another variant or all other variants except of current one that should be clicked to reveal it

**Comment by AttractLight** [comment]
Hidden text is a good idea! But do we need a Unicode code? Also how about always showing a collapsed area as an option? This might be tedious but it should prevent the existence of variants from becoming a hint. Just like this:

on 劍
<details>
<summary>Variants</summary>
剣 (shinjitai), 劔, 劒, 剱, 釼
</details>

on 雨
<details>
<summary>Variants</summary>
No kanji variants found on Kanji Dojo
</details>

**Comment by syt0r** [comment]
Unicode label is just to create some kind of distinguishing association so that user won't need to see other kanji variants and spoil its form. I was thinking to make this hidden text act like a spoiler on websites and messenger apps, like it's a gray box until you click it. I don't want to make it expandable because it will shift expressions

Do you think the stroke count label feature is still needed with if this feature is implemented?

**Comment by AttractLight** [comment]
Ah I see. I think the design issue is fixed now.

> Do you think the stroke count label feature is still needed with if this feature is implemented?

No

**Comment by syt0r** [comment]
Here what I'm planning to do

[Screencast from 15.02.24 11:51:28.webm](https://github.com/syt0r/Kanji-Dojo/assets/7478653/72977d2b-5157-48e9-90a6-ea848e9d201e)

**Comment by syt0r** [comment]
By the way, I just noticed one interesting thing with Japanese translation during practice, there can be situations when you are reviewing a character and it could be seen in the info section :sweat_smile:  like kanji from 訓音読、and some of characters used in variants description like 画 and 體 from 異體字. Can these labels be described using only kana in an understandable way or if it's clear enough for natives even use english translations here?
