### ISSUE TITLE
Vertical line recognition is too strict in some situations

### ISSUE THREAD

**Issue by ghost** [SYtor/Kanji-Dojo#96]
I faced this problem in 孵 and 叩, but iirc I didn't face it in 卵 and 卯 🤔

https://github.com/syt0r/Kanji-Dojo/assets/147967470/365140c1-227e-4b1b-87b4-4f2fc043c657

**Comment by sl08154711** [comment]
Yes and horizontal lines, too. See #75 and #88, which got merged right after version 1.9. In the meantime, try to draw the vertical or horizontal lines at a slight angle. Not much. Just a few degrees.

**Comment by AttractLight** [comment]
Gladly alternative evaluator fixed this issue. But it is too strict for me 😔 (after the rewrite PR merged too)

Also I haven't faced this when writing horizontal lines.

**Comment by syt0r** [comment]
Weird, I wonder if there is something different with the stroke path there, will check

**Comment by syt0r** [comment]
Just adjusted the algorithm a little. I noticed from logs that scale error was too big for these strokes and from debugging turned out kanji strokes in the database had width like 0.1 or 0.3 (with input size around 109), making most lines that you write too wide in comparison

I made it so that the app would make minimum stroke width/height=1, from my quick test it works alright for these 3 characters, let me know if there are other problematic places
